# Window info
WINDOW_SIZE = (800, 600)

# DEFAULT FUNCTION VALUES
DEF_FUNCTION = "sin(2*x)/x"
DEF_VARIABLE = "x"
DEF_START_VALUE = -5
DEF_END_VALUE = 5
DEF_PPU = 10

# Other definitions
DEF_PAD = 10
FUNCTION_ENTRY_WIDTH = 50
DEFAULT_ENTRY_WIDTH = 10