# Window info
WINDOW_SIZE = (700, 700)
MINIMUM_SIZE = (400, 400)

# DEFAULT FUNCTION VALUES
DEF_FUNCTION = "sin(x)/x"
DEF_VARIABLE = "x"
DEF_START_VALUE = -10
DEF_END_VALUE = 10
DEF_PPU = 10

# Other definitions
DEF_PAD = 10
FUNCTION_ENTRY_WIDTH = 50
DEFAULT_ENTRY_WIDTH = 10
DEFAULT_BACKGROUND = "black"
DEFAULT_LABEL_TEXT_COLOR = "white"